api地址与数据格式校对
zjutjh/boomerang-vue pull request #4
Opened 2018-07-24 15:21 UTC by xuguocong

2018-07-24 15:39 UTC, cccRaim commented
确定auto_login只传token？

2018-07-25 14:53 UTC, xuguocong commented
是只传token
自动登陆的文档是这样的
{
  code: 200,//成功
  error: null,
  data: {
    token: 'XXX'
  }
}

2018-07-25 16:34 UTC, cccRaim commented
不仅要校对mock里的数据，还要把显示的数据校对一下

2018-07-26 07:03 UTC, cccRaim requested changes

2018-07-26 07:03 UTC, cccRaim commented on src/api/map.js
> +  'detail': '/api/detail/id',
你这个应该写错了

2018-07-26 07:03 UTC, cccRaim commented on src/api/map.js
> +  'getUserInfo': '/api/auto_login',
你这个接口不能获取到用户的昵称吧，getUserInfo需要获取到用户的信息

2018-07-26 07:12 UTC, xuguocong commented on src/api/map.js
> +  'getUserInfo': '/api/auto_login',
我是根据文档来的啊。。。后端给我的地址就是/api/auto_login

2018-07-26 07:17 UTC, xuguocong commented on src/api/map.js
> +  'getUserInfo': '/api/auto_login',
还是说要把传过去的参数加在后面

2018-07-27 11:05 UTC, cccRaim commented on src/api/map.js
> +  'getUserInfo': '/api/auto_login',
@xuguocong 总不能autoLogin和getUserInfo是同一个地址吧。。。区分出两个地址还是有理由的

2018-07-30 04:11 UTC, cccRaim approved these changes

2018-07-30 04:11 UTC, merged